import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar/Navbar";
import Sidebar from "@/components/layouts/LeftSidebar/LeftSidebar";
import LeftSidebar from "@/components/layouts/LeftSidebar/LeftSidebar";
import RightSidebar from "@/components/layouts/RightSidebar/RightSidebar";
import ContextProvider from "@/providers/ContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-muted`}
      >
        <nav>
          <Navbar />
        </nav>
        <ContextProvider>
          {children}
        </ContextProvider>
        <footer></footer>
      </body>
    </html>
  );
}
