import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar/Navbar";
import Sidebar from "@/components/layouts/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-muted`}
      >
        <nav>
          <Navbar />
        </nav>
        <main className="flex relative">
        <aside className="h-screen bg-background w-[300px] left-0 p-10 fixed"><Sidebar /></aside>
        <section className="mx-[300px] p-10 w-full ">{children}</section>
        <aside className="w-[300px] h-screen fixed bg-background right-0">aside</aside>
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
